version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pain-league
      MYSQL_USER: brawler
      MYSQL_PASSWORD: nerf-edgar-plz
    volumes:
      - ./tmp/db:/var/lib/mysql

  db-test:
    image: mysql:8.0
    container_name: db-test
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pain-league-test
      MYSQL_USER: brawler-test
      MYSQL_PASSWORD: nerf-edgar-plz-test
    volumes:
      - ./tmp/db-test:/var/lib/mysql
